######################################################################
# Automatically generated by qmake (3.1) Sat Jul 13 14:52:29 2024
######################################################################

TEMPLATE = app
TARGET = project_zanella
INCLUDEPATH += .
QT += widgets
QT += core gui charts

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += src/json/jsonmanager.h \
           src/json/jsonreader.h \
           src/logic/errormanager.h \
           src/ui/mainpanel.h \
           src/ui/mainwindow.h \
           src/ui/toolbar.h \
           src/ui/upperbar.h \
           src/json/interfaces/ijsonmanagerobserver.h \
           src/json/json_writer_visitor/jsonwritervisitor.h \
           src/logic/distribution/distribution.h \
           src/logic/sensor/sensor.h \
           src/logic/sensor/sensorsmanager.h \
           src/ui/catalogue/cataloguepanel.h \
           src/ui/catalogue/infopanel.h \
           src/ui/catalogue/pagecontrollerpanel.h \
           src/ui/catalogue/sensorpanel.h \
           src/ui/catalogue/sensorspage.h \
           src/ui/log/criticalmessagelog.h \
           src/ui/log/messagelog.h \
           src/ui/log/warningmessagelog.h \
           src/ui/options/createpanel.h \
           src/ui/options/optionspanel.h \
           src/ui/options/searchpanel.h \
           src/logic/distribution/distributiontypes/exponentialdistribution.h \
           src/logic/distribution/distributiontypes/normaldistribution.h \
           src/logic/distribution/distributiontypes/uniformdistribution.h \
           src/logic/distribution/interfaces/idistributionconstvisitor.h \
           src/logic/distribution/interfaces/idistributionvisitor.h \
           src/logic/sensor/interfaces/isensorconstvisitor.h \
           src/logic/sensor/interfaces/isensorobserver.h \
           src/logic/sensor/interfaces/isensorsmanagerobserver.h \
           src/logic/sensor/interfaces/isensorvisitor.h \
           src/logic/sensor/sensortypes/heatsensor.h \
           src/logic/sensor/sensortypes/lightsensor.h \
           src/logic/sensor/sensortypes/watersensor.h \
           src/ui/catalogue/modification/modificationpanel.h \
           src/ui/catalogue/simulation/simulationpanel.h \
           src/ui/options/filter_visitor/filtervisitor.h \
           src/ui/catalogue/modification/info_visitors/distributioninfovisitor.h \
           src/ui/catalogue/modification/info_visitors/sensorinfovisitor.h \
           src/ui/catalogue/modification/set_visitors/distributionsetvisitor.h \
           src/ui/catalogue/modification/set_visitors/sensorsetvisitor.h \
           src/ui/catalogue/simulation/visitor/simulationvisitor.h
SOURCES += src/main.cpp \
           src/json/jsonmanager.cpp \
           src/json/jsonreader.cpp \
           src/logic/errormanager.cpp \
           src/ui/mainpanel.cpp \
           src/ui/mainwindow.cpp \
           src/ui/toolbar.cpp \
           src/ui/upperbar.cpp \
           src/json/json_writer_visitor/jsonwritervisitor.cpp \
           src/logic/distribution/distribution.cpp \
           src/logic/sensor/sensor.cpp \
           src/logic/sensor/sensorsmanager.cpp \
           src/ui/catalogue/cataloguepanel.cpp \
           src/ui/catalogue/infopanel.cpp \
           src/ui/catalogue/pagecontrollerpanel.cpp \
           src/ui/catalogue/sensorpanel.cpp \
           src/ui/catalogue/sensorspage.cpp \
           src/ui/log/criticalmessagelog.cpp \
           src/ui/log/messagelog.cpp \
           src/ui/log/warningmessagelog.cpp \
           src/ui/options/createpanel.cpp \
           src/ui/options/optionspanel.cpp \
           src/ui/options/searchpanel.cpp \
           src/logic/distribution/distributiontypes/exponentialdistribution.cpp \
           src/logic/distribution/distributiontypes/normaldistribution.cpp \
           src/logic/distribution/distributiontypes/uniformdistribution.cpp \
           src/logic/sensor/sensortypes/heatsensor.cpp \
           src/logic/sensor/sensortypes/lightsensor.cpp \
           src/logic/sensor/sensortypes/watersensor.cpp \
           src/ui/catalogue/modification/modificationpanel.cpp \
           src/ui/catalogue/simulation/simulationpanel.cpp \
           src/ui/options/filter_visitor/filtervisitor.cpp \
           src/ui/catalogue/modification/info_visitors/distributioninfovisitor.cpp \
           src/ui/catalogue/modification/info_visitors/sensorinfovisitor.cpp \
           src/ui/catalogue/modification/set_visitors/distributionsetvisitor.cpp \
           src/ui/catalogue/modification/set_visitors/sensorsetvisitor.cpp \
           src/ui/catalogue/simulation/visitor/simulationvisitor.cpp
RESOURCES += src/ui/resources.qrc
